version: '3.8'

services:

  api:
    build: .
    command: flask --app lyrics_analytics.api --debug run -h 0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - BROKER_URL=amqp://guest:guest@rabbit:5672/
      - CACHE_HOST=redis
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - rabbit
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    restart: always

  rabbit:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always

volumes:
  redis-data:
  rabbitmq-data: