version: '3.8'

services:

  api:
    build: .
    command: flask --app lyrics_analytics.api --debug run -h 0.0.0.0
    env_file:
      - .dev.env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  worker:
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
    command: celery -A lyrics_analytics.api.celery worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    restart: unless-stopped

  mongo:
      image: mongo
      restart: unless-stopped
      environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=pass
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/var/lib/mongo-data

  rabbit:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://user:pass@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=redis
    depends_on:
      - redis

volumes:
  redis-data:
  mongo-data:
  rabbitmq-data:
