version: '3.8'

services:

  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - redis
      - rabbit
    networks:
      rabbit-network:

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      rabbit-network:

networks:
  rabbit-network:
    driver: bridge
