[tool.poetry]
name = "lyrics-analytics"
version = "0.1.0"
description = ""
authors = ["Anton <antongb09@gmail.com>"]
readme = "README.md"
packages = [{include = "lyrics_analytics"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
poetry-dotenv-plugin = "^0.1.0"
flask = "^2.2.2"
beautifulsoup4 = "^4.11.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
